thomasjo/atom-latex

lib/composer.js, lib/parsers/log-parser.js, lib/views/error-indicator-view.js, spec/parsers/log-parser-spec.js
See https://github.com/thomasjo/atom-latex/issues/82.
/cc @nscaife @myfavouritekk
=> Open log file when clicking error indicator

lib/config-schema.js, lib/latex.js, spec/latex-spec.js
Inspired by https://github.com/daskelly/atom-latex/commit/bc1c7ef21239e97374e96146174cd7eb5b779099.
Only supports the `AtomPdfOpener` right now, but at some point it might be necessary to expand that. Also not entirely sure whether to call the option `alwaysOpenResultInAtom` or `preferOpeningResultInAtom` or some such variation thereof. Might be necessary to add a description to the option as well, stating the option will only be used if the `pdf-view` package is actually installed.
/cc @daskelly
=> Add option for always opening result in Atom

lib/builders/texify.js
Currently `TexifyBuilder` has some incorrect feature flags, as well as functionality that is not (properly) supported by `texify` such as engine customizations and `--output-directory`.
The problematic functionality is removed and instead replaced with notifications to let the user know they are using unsupported functionality. I wish there was a better way, but configuration is still a static concept in Atom, so for the time being this way of handling unsupported config combinations will suffice.
=> Tweak TexifyBuilder

lib/openers/custom-opener.js
If ${filePath} contains spaces most PDF viewers, e.g. evince, will not treat it as a single argument. Wrapping the path in quotation marks fixes that issue.
=> Wrap custom opener file path in quotation marks to support spaces.

README.md, lib/config-schema.js, lib/latex.js, lib/openers/okular-opener.js
Checks for `linux` platform, also allows the user to input a custom path to the viewer
=> Add Okular Viewer support for linux

lib/builders/latexmk.js, lib/config-schema.js, spec/builders/latexmk-spec.js
Hi, I have added an option to create ps or dvi files instead of the default pdf when using the latexmk builder. Currently, this only works for latexmk, since I do not have access to texify.
=> Add support for ps and dvi file formats for latexmk builder

lib/composer.js
The clean command now take the custom build directory into account.
=> Clean uses now custom build directory

lib/main.js, package.json
Since the config schema is now stored in package.json, we can reintroduce delayed package activation without compromising the user experience.
From a development perspective this simplifies the code, and also reduces the level of Magic™ :sparkles:
=> Reintroduce (proper) delayed package activation

lib/composer.js, lib/error-marker.js, lib/parsers/log-parser.js, spec/parsers/log-parser-spec.js, styles/markers.atom-text-editor.less
Implemented markers #165. Along the way there was an issue with the way log parser was parsing #166 which is fixed.
=> Marker implementation

lib/openers/atompdf-opener.js
I recently got a [PR](https://github.com/izuzak/atom-pdf-view/pull/111) merged into atom-pdf package which allows forward syncing. This patch provides the second part of the functionality that allows a user to forward sync to the Atom PDF viewer.
I don't write JS frequently so let me know if I should change anything :smiley:
=> Add forward sync support to Atom PDF opener

lib/main.js, package.json
This PR is meant to augment #152, to fix edge case bugs, but also to improve the existing disposable setup in `main.js`. /cc @ravinrabbid
conjunction with multi-file documents, and similar scenarios.
---
Closes #152 
Resolves #150
=> Tweak #152

lib/config-schema.js, lib/openers/sumatra-opener.js
* Simply adds `-inverse-search` flag to the SumatraPDF command that `sumatra-opener.js` generates
* Inverse search means double clicking inside the generated SumatraPDF document generates a command to open the source document in Atom at the source line that produced it
* __Tested on Windows only__ -- based the command line statement found at the bottom of [this discussion](https://discuss.atom.io/t/inverse-search-with-sumatrapdf/20076/2)
* Had to add a setting for the path to the Atom executable in order to complete the arguments to the `-inverse-search` flag
=> Added inverse-search functionality for sumatra-opener

lib/builder-registry.js, lib/builder.js, lib/builders/latexmk.js, lib/builders/texify.js, lib/composer.js, lib/latex.js, spec/build-registry-spec.js, spec/builder-spec.js, spec/composer-spec.js, spec/latex-spec.js
This is an attempt to generalize the builder concept which will make it easy to implement file type specific builders, which is currently needed in #144.
/cc @m0nhawk
---
directory.
for ones that can process the current file. Querying is done via abstract
`Builder.prototype.canProcess` method.
`LatexmkBuilder` and `TexifyBuilder`, but we need to choose one based on configuration.
Whether this should be done in the `BuilderRegistry::getBuilder` method or in the `Composer` needs
to be experimented with.
=> Generalize the builder concept

lib/builders/latexmk.js, lib/builders/texify.js, package.json, spec/builders/latexmk-spec.js
I love this package but I'm not a huge fan of SyncTeX, so I added an option to let me disable it. I thought I'd submit a PR in case you're interested in merging it.
=> Add config option for SyncTeX

lib/builder.js, lib/builders/latexmk.js, lib/builders/texify.js, lib/composer.js, spec/builder-spec.js, spec/composer-spec.js, spec/fixtures/magic-comments/latex-jobnames.tex
Add support for jobnames TeX Magic.  ``# !TEX jobnames = foo bar`` causes two builds. First with "foo" and second with "bar."
=> Jobname support

package.json
[language-latex](https://atom.io/packages/language-latex) has not been updated for a least a year. The fork [language-tex](https://atom.io/packages/language-tex) is being actively updated and there is also an alternate package [language-latexsimple](https://atom.io/packages/language-latexsimple).
=> Add other grammar activation hooks

keymaps/latex.json
The copy button in Atom's settings seems to assume keymaps are written in CSON
and does not escape single quotes.
Fixes #187
=> Use escaped double quotes in keymaps

lib/composer.js
Assignment of `outputFilePath` is missing in `resolveOutputFilePath`. I think this may have happened at the conversion from CoffeeScript to Javascript at 30a2dcb8a9a5e714ee026fc72ef741d7f578d46a
=> Assign outputFilePath in resolveOutputFilePath

lib/builder.js, lib/builders/texify.js
Only define `BIBTEX` variable if not defined system wide. Should fix #185
=> Add default environment for texify

.appveyor.yml, .travis.yml, lib/builders/knitr.js, script/cibuild, script/install-knitr, spec/build-registry-spec.js, spec/builders/knitr-spec.js, spec/fixtures/knitr/file.Rnw
This PR adds support for building Knitr/Sweave documents. It likely has some rough edges, but should be good enough for most users... 🎱
Hoping someone are willing to test this out. It seems to work quite well, but would love some feedback!
TODO:
-  ~~Add support for `latex.outputDirectory`.~~ _Turns out this isn't really necessary, nor useful. Output redirection is handled by `LatexmkBuilder` and `TexifyBuilder`._
---
Resolves: #101
=> Knitr support

.travis.yml
Migrate macOS builds on Travis CI to 10.11 and Xcode 8. This might (partially) fix #217.
=> Use Xcode 8 and macOS 10.11 on Travis CI

README.md, lib/composer.js
This PR officially deprecates our `texify` support. The user is presented with a fairly annoying warning notification. Clicking the button opens the wiki page ["Using-latexmk-with-MiKTeX"](https://github.com/thomasjo/atom-latex/wiki/Using-latexmk-with-MiKTeX).
=> Deprecate texify support

lib/latex.js, lib/openers/evince-opener.js, package.json
This PR addresses #162. It is currently a bit of callback hell, but SyncTeX forward and backward are working.
=> Add support for Evince with SyncTex

lib/composer.js, spec/composer-spec.js
Make `latex:clean` and `latex:sync` aware of jobnames.
Fixes #211.
=> Fix jobnames bugs associated with Sync and Clean

lib/builders/knitr.js, lib/builders/latexmk.js, lib/latex.js, lib/logger.js, lib/process-manager.js, spec/builders/knitr-spec.js, spec/builders/latexmk-spec.js
if `patchSynctex` is not available a warning is logged. Also, setting the output directory option appears to break `patchSynctex` so a warning for that might in order.
=> Add concordance and patchSynctex to KnitrBuilder

lib/parsers/log-parser.js, spec/builders/latexmk-spec.js, spec/fixtures/error-warning.tex, spec/fixtures/sub/wibble.tex
Current path resolution for error messages only works if the source file generating the error is in the same directory. It fails if the file is in a sub-directory or if the path contains a parent reference like `../foo`
=> Fix incorrect path resolution in LogParser

lib/builder-registry.js, lib/builder.js, lib/builders/knitr.js, lib/builders/latexmk.js, lib/builders/texify.js, lib/composer.js, lib/error-marker.js, lib/logger.js, lib/opener-registry.js, lib/parsers/log-parser.js, lib/views/log-message.js, lib/views/status-label.js, spec/builders/knitr-spec.js, spec/builders/latexmk-spec.js, spec/builders/texify-spec.js, spec/logger-spec.js, spec/loggers/default-logger-spec.js, spec/parsers/log-parser-spec.js
Expands the `checkEnvironment` function to do other checks besides deprecation notices and version migration. Since information checks are done also the messages are placed in the log versus using Atom notifications.
Current checks:
1. `latexmk` version check. Helps warn users about #243 situations. Also verifies that `latexmk` can be run outside of a build. [Error severity]
1. `Rscript` versions check. Mostly just to make sure `Rscript` can be run. [warning severity]
2. `knitr` and `patchSynctex` library check. [warning severity]
3. PDF capable viewer check. [error severity]
4. PS capable viewer check. [warning severity]
5. DVI capable viewer check. [warning severity]
Addresses some of #54 (does not automatically configure TeX path).
Resolves #62.
=> Check environment at startup

lib/composer.js, lib/config-migrator.js, lib/main.js, menus/latex.json, package.json
Move checks that were happening in `Composer` into `ConfigMigrator` to avoid race condition in the creation of `latex`.
=> Add configuration check and migrator

lib/builder.js, lib/error-marker.js, lib/logger.js, lib/loggers/default-logger.js, lib/parsers/log-parser.js, lib/process-manager.js, spec/builders/knitr-spec.js, spec/builders/latexmk-spec.js, spec/builders/texify-spec.js, spec/logger-spec.js
Decrease dependence on lodash by using more ES6/7 features
=> Use more ES6/7 features

lib/builder.js, lib/composer.js
Extend relative/absolute functionality to build, etc. Fixes #290.
=> Fix relative/absolute output path in build and clean

lib/openers/atril-opener.js, lib/openers/evince-opener.js, lib/openers/x-reader-opener.js, package.json
Add support for MATE's [Atril](https://github.com/mate-desktop/atril) and Cinnamon's [Xreader](https://github.com/linuxmint/xreader) forks of Evince. Since these forks use the same opening and SyncTeX logic just with different D-Bus names support is accomplished by sub-classing `EvinceOpener`. They do not support the `org.freedesktop.Application` interface used to activate the application, so open in background is probably not possible.
=> Add support for Evince forks

lib/builder.js, lib/builders/knitr.js, lib/builders/latexmk.js, lib/builders/texify.js
The call to `logStatusCode` got removed in v0.38.0. Moved it into the builders since `KnitrBuilder` doesn't know about status codes of `latexmk`.
=> Add logStatusCode calls

lib/builders/knitr.js, lib/builders/latexmk.js, lib/builders/texify.js, spec/builders/knitr-spec.js, spec/builders/latexmk-spec.js, spec/builders/texify-spec.js
Make sure `logStatusCode` gets called for failed builds.
=> Add checks for logStatusCode

lib/builders/knitr.js, spec/builders/knitr-spec.js
Use `syncfile` parameter added by EmmanuelCharpentier/patchSynctex#4 to enable SyncTex patching when using an output directory or a jobname.
=> Improve patch synctex

lib/process-manager.js
Add guard to process error log in case process is still running when package is disabled. Fixes #330.
=> Fix latex reference in ProcessManager

package.json, styles/markers.atom-text-editor.less
This PR rewrites deprecated Shadow DOM based selectors that will stop working in Atom v1.13.
Resolves #319
=> Remove usage of the Shadow DOM

lib/openers/okular-opener.js
Okular seems to want a url with a proper file protocol portion or it tries to escape the hash preceding the fragment.
Fixes #332.
=> Use file protocol in Okular

lib/builder.js
`latexmk` now runs xdvipdfmx separately so we need to look at the `xdvipdfmx` section in the FDB.
Fixes #339
=> Add xdvipdfmx section to FDB parse

lib/openers/evince-opener.js
Evince indexed the window based on the TeX path when it should be the output
path.
=> Fix Evince jobname support

lib/openers/sumatra-opener.js
Currently, the `-reuse-instance` flag appears to be needed when tabbed mode is off.
Fixes #347
Resolves #348
=> Improve SumatraPDF experience

.travis.yml
Beta channel appears to need GLIB 2.17 now
=> Fix beta channel in Travis CI

package.json
New version has `abstract-socket` as an optional dependency.
=> Update dbus-native to v0.2.1

lib/builder.js
`Builder` currently assumes that the main file path in `JobState` is the file path referred to in the log file produced by LaTeX. We could parse the concordance file and link to the original source like Rstudio. This will probably require changes to the log messaging format so it is probably best to leave that as an enhancement PR.
Fixes #370.
=> Fix Log References for Knitr

lib/composer.js, package.json
Atom's `TextEditor.save` is now async, and this PR addresses that change.
Since the change will land in Atom v1.19, the engine requirement was also updated accordingly.
Resolves #385
=> Adjust to upstream async API changes

README.md, lib/composer.js, lib/config-migrator.js, lib/main.js, lib/parsers/log-parser.js, lib/views/log-message.js, package.json, script/install-knitr, spec/composer-spec.js, spec/parsers/log-parser-spec.js
Add support for [DiCy](https://yitzchak.github.io/dicy/) without changing current behavior of atom-latex.
=> Add basic support for DiCy builder

lib/builder.js
Use the main knitr source file if the generated LaTeX file is missing. Resolves #386
=> Ignore missing LaTeX file during log parsing

lib/composer.js
If editor focus changes during the build then calls to the opener in `showResult` may get the wrong `filePath` and `lineNumber` so call `getEditorDetails` just once before the build begins.
=> Fix forward sync during build for multiple job names

lib/openers/pdf-view-opener.js, package.json
Prevent multiple splitting of pdf-view and add `pdfViewSplitDirection` configuration. Fixes #397.
=> Fix pdf-view opener splitting

CHANGELOG.md, lib/openers/pdf-view-opener.js
Respect `openInBackground` setting by saving and re-activating previous pane. Resolves #413
=> Fix pdf-view focus

CHANGELOG.md, lib/logger.js, lib/marker-manager.js, spec/logger-spec.js, spec/marker-manager-spec.js
The reset flag is getting lost because Atom's Emitter only handles one event value. Fix this by wrapping the event data with a single object and destructure in the event handlers. Fixes #419.
=> Fix marker reset issue

lib/main.js
In Atom 1.21, the package disposal appears to be happening before the status bar disposes of our indicator.  Using `global.latex` in the disposal function resolves this. Fixes #417.
=> Use global reference to latex in dispose

README.md
This is required to make working with Latex documents much more usable. Also, the keybindings didn't work for me when the language-latex package was not installed.
=> Extends requirements to properly function

lib/parsers/log-parser.js, spec/builders/latexmk-spec.js, spec/fixtures/error-warning.tex, spec/fixtures/sub/foo bar.tex, spec/fixtures/sub/wibble.tex
This is an experimental PR that attempts to (somewhat naively) parse the markers in the log from `\input` and `\include` so as to more accurately determine the source file for warning messages.
The motivating issue is #430.
=> Parse input source markers in log

lib/composer.js, package.json, spec/composer-spec.js
=> Update DiCy and add fast load

script/install-knitr, spec/async-spec-helpers.js, spec/build-registry-spec.js, spec/builder-spec.js, spec/builders/knitr-spec.js, spec/builders/latexmk-spec.js, spec/composer-spec.js, spec/latex-spec.js, spec/logger-spec.js, spec/marker-manager-spec.js, spec/opener-registry-spec.js, spec/parsers/fdb-parser-spec.js, spec/parsers/log-parser-spec.js, spec/parsers/magic-parser-spec.js, spec/process-manager-spec.js
I shamelessly procured the [`async-spec-helpers.js`](https://raw.githubusercontent.com/atom/atom/master/spec/async-spec-helpers.js) file from Atom, and migrated all of our specs to leverage those async helpers.
This PR represents a small step towards eventually upgrading Jasmine to a modern release, or perhaps migrating to Mocha + Sinon and what not.
All specs (except SageTeX and Asymptote) are green on my Ubuntu 17.04 system, using TeX Live 2017.
=> Migrate specs to use async helpers

lib/openers/qpdfview-opener.js, package.json
Hi i created a opener for qpdfview with synctex and appendend the package.json file with what i think is the appropriate information. It's really just a modified zathura-opener
this is my first time contributing so i might have made a fool of my self though.
=> Added qpdfview with synctex 

package.json
@thomasjo
See https://discuss.atom.io/t/the-event-stream-incident-and-the-atom-teams-response/60807/3 and  https://github.com/sidorares/dbus-native/issues/253
=> Update dbus to remove flatmap vulnerability

README.md, lib/builders/latexmk.js, package.json
(tries to) Fixes https://github.com/thomasjo/atom-latex/issues/480
Honestly, I have only tried this with a single file and no included / inputed / other fancy projects. That's why I want to leave the option disabled by default, but there if a user experiences the same issue as above.
I will report back with more attempts to break it, but I don't think I can test all combinations of files this package supports (sage, knitr, etc.). It doesn't help that these tests are failing anyway for me (I suppose it's because I don't have those programs installed? IDK).
=> Add relative path support
