- lib/builder.js
- lib/builders/latexmk.js
- lib/composer.js
- spec/builders/latexmk-spec.js
Second attempt at fixing #87, this time with a simpler approach that should work as intended across platforms. Again, would be really great if people can test this to verify that it works as intended.
Will :boat: this tonight unless someone finds a bug or some such.
> Fix working directory issue (redux)

- README.md
- lib/builders/texify.js
- lib/config-schema.js
- lib/latex.js
- lib/loggers/console-logger.js
- lib/openers/custom-opener.js
- spec/composer-spec.js
- spec/latex-spec.js
Two new features:
- support for texify compiler as a second Builder
- support for user-specified viewer as additional Opener
And a small fix for running specs on windows.
> texify and user-specified PDF-viewer

- README.md
- lib/builder.js
- lib/builders/latexmk.js
- lib/parsers/magic-parser.js
- spec/builder-spec.js
- spec/fixtures/magic-comments/latex-engine.tex
- spec/fixtures/magic-comments/multiple-magic-comments.tex
- spec/parsers/magic-parser-spec.js
Hey,
I had some time at work today and needed the functionality for the engine switch magic comment. So I updated the stuff. Also added the multiple magic comments and magic comments anywhere before a first latex command.
See #106
> Multiple magic comments & Engine change support

- lib/builders/texify.js
I have fixed the `texify` builder for MikTeX.
> engine from magic support for texify

- lib/openers/sumatra-opener.js
I've also fixed the Sumatra opener, it was broken in 0.28
> Fix sumatra opener on Windows

- README.md
I had to find the instructions from a Github issue someone else made, I think this information should be in the Readme.
> Clarified instructions for MiKTeX users

- lib/parsers/magic-parser.js
> Magic regex matches TeX and TEX

- .appveyor.yml
- README.md
- script/cibuild
- script/install-texlive
- script/lint
- spec/parsers/log-parser-spec.js
This PR reintroduced CI builds on AppVeyor — in other words, we are once again running CI builds on the Windows platform 🎉
After they migrated to their new infrastructure, builds have been super-fast and stable. Awesome job by the AppVeyor team!
> Reintroduce AppVeyor

- lib/composer.js
> Update getBuilder reference

- lib/composer.js
Fix #197 probably caused by #195
> Add missing getBuilder argument

- lib/composer.js
- lib/latex.js
- lib/opener.js
- lib/openers/atompdf-opener.js
- lib/openers/custom-opener.js
- lib/openers/evince-opener.js
- lib/openers/okular-opener.js
- lib/openers/preview-opener.js
- lib/openers/skim-opener.js
- lib/openers/sumatra-opener.js
- lib/openers/xdg-opener.js
- lib/werkzeug.js
- spec/latex-spec.js
Use as final fallback on Linux. Replaces #38 and resolves #123.
> Add opener based on xdg-open

- lib/builder.js
- lib/builders/knitr.js
- lib/builders/latexmk.js
- lib/composer.js
- lib/main.js
- menus/latex.json
- spec/builders/latexmk-spec.js
Rebuild command (`-g` option) is only available from menu or forced by any changes to the `latex` config. 
Resolves #112.
> Add rebuild command

- lib/builder.js
- spec/fixtures/file.fdb_latexmk
- spec/fixtures/file_win32.fdb_latexmk
- spec/parsers/fdb-parser-spec.js
Fix the regex problem causing #245.
> Fix extension regex

- lib/builder.js
- lib/builders/knitr.js
- lib/builders/latexmk.js
- lib/builders/texify.js
- lib/composer.js
- lib/latex.js
- lib/loggers/default-logger.js
- lib/main.js
- lib/process-manager.js
- lib/views/status-indicator.js
- menus/latex.json
- package.json
- spec/process-manager-spec.js
:bulb: This PR is the kernel of an idea for a method of resolving #236.
> Add Process Manager

- lib/composer.js
- lib/latex.js
- lib/loggers/default-logger.js
- lib/main.js
- lib/status-indicator.js
- lib/views/status-label.js
Make a separate class like `ProcessManager`.
> Move status bar view out of Latex class

- lib/composer.js
Check for knitr files in sync command. resolves #251
> Support synctex for Knitr files

- lib/builder.js
- lib/views/log-message.js
- script/install-knitr
PR to fix our various CI issues.
> Fix CI issues

- lib/builder.js
- lib/builders/knitr.js
- lib/composer.js
- spec/builder-spec.js
- spec/builders/latexmk-spec.js
- spec/builders/texify-spec.js
- spec/composer-spec.js
- spec/fixtures/magic-comments/override-settings.tex
Resolves #104. Mentioned in #178.
> Switch to relative output dir and add output magic

- lib/builder.js
- lib/openers/okular-opener.js
Also add background open for Okular
> Improve output path logic

- lib/openers/evince-opener.js
> Add decode/encode URI to Evince

- script/cibuild
- script/install-miktex
- script/install-texlive
This PR is an attempt to use a custom MiKTeX portable distribution to speed up the AppVeyor CI for MiKTeX.
> MiKTeX Portable CI

- lib/builder-registry.js
- lib/builders/knitr.js
- lib/builders/latexmk.js
- lib/composer.js
- lib/latex.js
- lib/loggers/default-logger.js
- lib/main.js
- lib/opener-registry.js
- lib/opener.js
- lib/openers/evince-opener.js
- lib/openers/skim-opener.js
- lib/process-manager.js
- lib/status-indicator.js
- lib/views/status-label.js
- package.json
- spec/build-registry-spec.js
- spec/composer-spec.js
Some possible fixes for #268. Fixes #283.
> Add guard for log panel hide

- package.json
Set minimum Atom version of 1.10.0. Resolves #293.
> Set minimum Atom version

- lib/builders/latexmk.js
- spec/builders/latexmk-spec.js
> Use -xelatex and -lualatex options

- lib/composer.js
- spec/composer-spec.js
> Fix matching for relative output directory

- lib/openers/pdf-view-opener.js
Try to fix pdf-view SyncTex. First add missing arguments to `forwardSync`.
#209
> Fix pdf-view SyncTeX

- lib/openers/shell-open-opener.js
- package.json
> Add win32 shell open

- lib/builders/knitr.js
- lib/openers/preview-opener.js
- lib/parsers/fdb-parser.js
- lib/parsers/log-parser.js
Fix some lint errors occuring in CI.
> Fix lint issues

- script/install-knitr
choco seems to require checksums now.
> Fix Appveyor R install

- lib/openers/evince-opener.js
Complete switch of keying of Evince window from using LaTeX path to using DVI/PS/PDF path.
> Fix Evince Window Disposal

- lib/openers/evince-opener.js
Add window focus on reverse sync for Evince.
Resolves #354
> Refocus Atom on Evince Reverse Sync

- script/cibuild
> Fix AppVeyor XZ

- lib/views/log-dock.js
- styles/latex.less
Just a few tweaks to improve the log table.
> Improve Log Table

- .travis.yml
- script/install-texlive
> Fix Asymptote in Travis CI

- README.md
Also add some links to DiCy documentation.
> Add some documentation regarding build paths

- CHANGELOG.md
- lib/composer.js
- spec/composer-spec.js
> Fix cleaning of hidden files

- lib/werkzeug.js
> Add tikz extension

- lib/builders/knitr.js
- lib/composer.js
- lib/logger.js
- lib/openers/evince-opener.js
- lib/openers/okular-opener.js
- lib/werkzeug.js
- package.json
- spec/builders/knitr-spec.js
- spec/composer-spec.js
This is an experimental PR which uses a JSON-RPC interface to DiCy.
> Use DiCy RPC
